### ISSUE TITLE
Bottom White bar - (Samsung S3 thru S6) 

### ISSUE THREAD

**Issue by derekguay13** [mesmotronic/air-ane-fullscreen#23]
When I use the ANE the status bar disappears as expected but a white bar the same size as the status bar shows up at the bottom.  

This happens on all 4 phones I've tested. (Samsung S3 thru S6)

I'm sure I'm doing something wrong.

A similar issue is I get what I think is the samsung legacy menu icon when I publish too. (A semi trans parent circle with 3 dots in it.)  Can this be gotten rid of?

Thanks.

**Comment by neilrackett** [comment]
The coloured bar issue is usually caused by `<fullScreen>true</fullScreen>` in the app XML or setting `stage.displayMode = StageDisplayMode.FULL_SCREEN` before switching to immersive mode.

If it's not that, there are a number of similar topics in the closed issues list that might be worth taking a look at.

**Comment by neilrackett** [comment]
After further investigation, the most likely cause is that you are using stage.scaleMode = StageScaleMode.SHOW_ALL (the default scale mode) with a 16:10 ratio stage (default size Flash template) and a 16:9 ratio screen.

The solution is to use a 16:9 ratio stage or switch scale mode to NO_BORDER.
