### ISSUE TITLE
This ANE is now deprecated

### ISSUE THREAD

**Issue by neilrackett** [mesmotronic/air-ane-fullscreen#32]
Adobe AIR will use immersive mode full screen by default from version 23: http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air23_flashplayer23_releasenotes.pdf

As this is the primary use case for this ANE, there's unlikely to be any further development, so we'd like to say a  big thanks to everyone that's supported this project over the past few years!

**Comment by gene-pavlovsky** [comment]
I just tested my project with AIR 23 and it does use immersive fullscreen by default. However when I swipe from the top or bottom, system status bar is revealed but navbar is not revealed. Any pointers? Should I try process swiping from top/bottom myself, and exit fullscreen if such a gesture is detected?

**Comment by neilrackett** [comment]
AIR 23 does use immersive full screen, but there's a bug using direct render mode that means you end up with a black bar where the navigation bar was; see https://bugbase.adobe.com/index.cfm?event=bug&id=4100625

For now, I'd recommend continuing to use this ANE until the bug is resolved (and voting for the big on Adobe bug base).

**Comment by gene-pavlovsky** [comment]
Thanks for your answer, Neil. Strangely, I'm not experiencing this issue. My app truly occupies the entire available screen. But there's no way to show up the navbar, unless I exit fullscreen mode (I guess, haven't tried yet).

**Comment by gene-pavlovsky** [comment]
Thanks for your answer, Neil. Strangely, I'm not experiencing this issue. Isn't it marked as fixed in SDK 23 release notes? My app truly occupies the entire available screen. But there's no way to show up the navbar, unless I exit fullscreen mode (I guess, haven't tried yet).

**Comment by neilrackett** [comment]
Yes, the issue is described as fixed in the AIR 23 release notes and works perfectly in CPU and GPU render modes, but we're still seeing problems using direct here.

I just tried a quick test app on a couple of devices here, but haven't been able to replicate the issue you described (the nav and status bar always appear after a swipe from the top/right) and I don't think it would be very easy to replicate the functionality using an ANE because it's (supposed to be) handled by the system, rather than the app, so I'm not able to offer up any simple solutions at the moment, unfortunately.

**Comment by gene-pavlovsky** [comment]
All right, thank you Neil.

**Comment by timoisalive** [comment]
Hi, and thanks for your work with this issue!

I'm just updating my app from AIR 19, ran into AIR 23/24 changes and am a little confused.

Is the previous fullscreen mode now altogether gone? I mean the mode where the statusbar is hidden, but the navigation bar is present and shows three little dots for the nav buttons. I don't seem to be able to get into that mode anymore and was wondering is this because of AIR or Android...

Also, your ANE enables the "lean mode" and "show under system ui" modes. How come is the ANE deprecated if these modes are not supported by AIR? Or am I just not finding the right api's...?

**Comment by neilrackett** [comment]
Hi @timoisalive,

Yes: the previous full screen mode no longer exists in AIR 23+, which use immersive mode full screen by default on Android 4.4+

As far as we're aware, most people only use this ANE for immersive mode in AIR <23, which is why we deprecated it, but if there's enough demand out there for the other full screen modes (and perhaps one or 2 new ones), we'll happily un-deprecate it (or rename this issue at least ;-)

**Comment by timoisalive** [comment]
Ok, that's too bad the previous full screen mode no longer exists... Is this something that you could achieve with the ANE though?

I think showUnderSystemUI() at least is really valuable, I think we'll go for that mode if the previous mode is out of question, even if it introduces it's own problems. Isn't the back button important for Android users anymore...?

I think only for the showUnderSystemUI() feature this ANE is still useful, and if you would be able to re-incarnate the previous full screen mode on top, this ANE would be totally valid!

**Comment by DFABRIK** [comment]
hits me with error on embedding splash jpg on stage on andriod 6.0.1
4.2.2 android working like a charm.
using this ANE and airsdk23, tried on 22 also its the same

any clue// tnx

**Comment by neilrackett** [comment]
Possibly related to Adobe's recent change in target Android SDK, but then I'm not sure why that would affect SDK 22. Hmmm...

**Comment by cgascons** [comment]
> AIR 23 does use immersive full screen, but there's a bug using direct render mode that means you end up with a black bar where the navigation bar was; see https://bugbase.adobe.com/index.cfm?event=bug&id=4100625

For now, I'd recommend continuing to use this ANE until the bug is resolved (and voting for the big on Adobe bug base).

It's already marked as closed/fixed but we are still experiencing width issues when using AIR 24 (build 180)

**Comment by timoisalive** [comment]
Hi again @neilrackett!

We're now in a little bit of trouble because of the changes in Android fullscreen experience in AIR 23.

If I understood correctly, our current display mode choices are:

1. Normal mode (status and nav bars visible)
2. Extend app under the status and nav bars
3. Immersive mode (status and nav bars invisible)

Unfortunately all of them introduce issues to our app.

1. Normal mode is terrible in landscape orientation on phones; status bar takes away a large slice of real estate
2. Extending the app under the bars breaks our layout which we use for both iOS and Android
3. Immersive fullscreen mode is problematic, because whenever the keyboard is needed, the navigation bar also pops up (I haven't yet found a way how to hide it again)

Also with both modes 2. and 3., the soft keyboard height seems not to be true anymore.

We would really be happy to see the old fullscreen mode as an option, where the status bar was invisible and navigation bar was dimmed.

Is there any way this ANE could be extended to offer such mode...?

**Comment by neilrackett** [comment]
Hi @timoisalive,

With immersive mode now available in AIR 23+, we're looking at the possibility making Android's [`setSystemUiVisibility`](https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int)) method available via AIR instead, which would potentially enable users to configure whichever full screen mode they like.

**Comment by timoisalive** [comment]
@neilrackett That would be perfect! Do you have any schedule planned for this feature? We're getting ready to release a major update, would be great to get this in...

**Comment by neilrackett** [comment]
I'm hoping to have time over the next 1-2 weeks to take a look, but there's no official schedule.

**Comment by timoisalive** [comment]
Right, of course, no pressure. Good to hear though, hope it'll be an easy one to crack! :)

**Comment by timoisalive** [comment]
Please do let us know for example by updating this thread whenever any news! Thanks a bunch! :)

**Comment by neilrackett** [comment]
Deprecated no more, check out [release 1.5.0](https://github.com/mesmotronic/air-ane-fullscreen/releases/tag/v1.5.0), which adds the new `setSystemUiVisibility` method.

@timoisalive the call you need is `AndroidFullScreen.setSystemUiVisibility(AndroidFullScreen.SYSTEM_UI_FLAG_FULLSCREEN | AndroidFullScreen.SYSTEM_UI_FLAG_LOW_PROFILE)`

**Comment by timoisalive** [comment]
Hey @neilrackett thanks a lot for your effort!

However, I'm unfortunately having trouble with the new release. Having updated the ANE, the app quits as soon as it launches. It shows black screen for half a second and closes. I'm not even calling the ANE, I'm only including it in the compilation. :(

**Comment by neilrackett** [comment]
Can you post that as a new issue, including your AIR SDK version, Android version, device manufacturer/model, the IDE you're using, etc?
